---
# Defines tasks applicable for postgreSQL

- name: Install Postgres
  package: name={{ item }} state=installed
  loop:
    - postgresql-server
    - postgresql-contrib
    - python-psycopg2
  tags:
    - dependencies
  
- name: init postgresql db
  command: /usr/bin/postgresql-setup initdb
  args:
    creates: /var/lib/pgsql/data/pg_hba.conf

- name: Configure postgresql for password authentication
  replace:
    backup: yes
    regexp: "^(host.*)ident$"
    replace: '\1md5'
    path: /var/lib/pgsql/data/pg_hba.conf
  tags: postgresql
  notify: restart postgresql

- name: Start postgresql
  service: name=postgresql state=started enabled=yes
  tags: postgresql

- name: Set password for PostgreSQL admin user
  become: true
  become_user: postgres
  postgresql_user: name={{ db_admin_username }} password={{ db_admin_password }} encrypted=yes
  tags: postgresql


