- name: Install fail2ban packages
  package: name=fail2ban state=installed
  tags:
    - dependencies

  name: Copy fail2ban configuration into place
  template: src=etc_fail2ban_fail2ban.d_00-local.conf.j2 dest=/etc/fail2ban/fail2ban.d/00-local.conf
  notify: restart fail2ban

- name: Ensure fail2ban is started
  service: name=fail2ban state=started enabled=yes
