---
# Defines tasks applicable for Chrony

- name: Install chrony
  package: name=chrony state=present
  tags:
    - dependencies

- name: Remove unwanted NTP pools
  lineinfile:
    path: /etc/chrony.conf
    state: absent
    regexp: '^server (?!{{ item }}) iburst$'
  loop: "{{ ntp_servers|flatten(levels=1) }}"
  notify: restart chronyd
  tags: chrony

- name: Add custom NTP entries
  lineinfile: 
    path: /etc/chrony.conf
    line: 'server {{ item }} iburst'
  loop: "{{ ntp_servers|flatten(levels=1) }}"
  notify: restart chronyd
  tags: chrony
    
- name: Remove bad chrony network access lines
  lineinfile:
    state: absent
    path: /etc/chrony.conf
    regexp: '^bindcmdaddress=(?!{{ item }})'
  loop: 
    - 127.0.0.1
    - ::1
  notify: restart chronyd
  tags: chrony

- name: Restrict chrony network access
  lineinfile:
    path: /etc/chrony.conf
    line: 'bindcmdaddress {{ item }}'
  loop: 
    - 127.0.0.1
    - ::1
  notify: restart chronyd
  tags: chrony



- name: Make sure chrony is enabled
  service: name=chronyd enabled=yes
  tags: chrony
