---
# Adds firewalld ports

- name: Install firewalld
  package: name=firewalld state=present
  tags: dependencies

- name: Set firewall rules for SSH
  firewalld: service={{ item }} permanent=true state=enabled
  loop:
    - ssh
  tags: firewalld

- name: Enable firewalld
  service: name=firewalld enabled=yes state=started
  tags: firewalld
