- name: Install necessities and nice-to-haves
  package: name={{ item }} state=installed
  loop:
    - git
    - htop
    - iftop
    - iotop
    - mosh
    - screen
    - sudo
    - vim
    - whois
    - lynis
    - rkhunter
    - net-tools
  tags:
    - dependencies

