  

- name: restart dovecot
  service: name=dovecot state=restarted

- name: restart opendkim
  service: name=opendkim state=restarted

- name: restart solr
  service: name=tomcat7 state=restarted
 


- name: restart rspamd
  service: name=rspamd state=restarted
