- name: Create live directory for testing keys
  file: dest=/etc/letsencrypt/live/{{ domain }} state=directory
    owner=root group=root mode=0755
  when: ansible_ssh_user == "vagrant"

- name: Copy SSL wildcard private key for testing
  copy: src=/root/ssl/wildcard_private.key
    remote_src=yes
    dest=/etc/letsencrypt/live/{{ domain }}/privkey.pem
    owner=root group=ssl-cert mode=0640
  register: private_key
  when: ansible_ssh_user == "vagrant"

- name: Copy SSL public certificate into place for testing
  copy: src=/root/ssl/wildcard_public_cert.crt
    remote_src=yes
    dest=/etc/letsencrypt/live/{{ domain }}/cert.pem
    group=root owner=root mode=0644
  register: certificate
  #notify: restart apache
  when: ansible_ssh_user == "vagrant"

- name: Copy SSL CA combined certificate into place for testing
  copy: src=/root/ssl/wildcard_ca.crt
    remote_src=yes
    dest=/etc/letsencrypt/live/{{ domain }}/chain.pem
    group=root owner=root mode=0644
  register: ca_certificate
  #notify: restart apache
  when: ansible_ssh_user == "vagrant"

- name: Create a combined SSL cert for testing
  shell: cat /etc/letsencrypt/live/{{ domain }}/cert.pem
    /etc/letsencrypt/live/{{ domain }}/chain.pem >
    /etc/letsencrypt/live/{{ domain }}/fullchain.pem
  when: (private_key.changed or certificate.changed or ca_certificate.changed) and ansible_ssh_user == "vagrant"

- name: Set permissions on combined SSL public cert
  file: name=/etc/letsencrypt/live/{{ domain }}/fullchain.pem mode=0644
  #notify: restart apache
  when: ansible_ssh_user == "vagrant"