- name: Get an SSL certificate for {{ domain }} from Let's Encrypt
  script: letsencrypt-gencert {{ domain }} creates=/etc/letsencrypt/live/{{ domain }}/privkey.pem
  when: ansible_ssh_user != "vagrant"

- name: Modify permissions to allow ssl-cert group access
  file: path=/etc/letsencrypt/archive owner=root group=ssl-cert mode=0750
  when: ansible_ssh_user != "vagrant"
