- name: Add group name ssl-cert for SSL certificates
  group: name=ssl-cert state=present
  tags: letsencrypt

- name: Download LetsEncrypt release
  git: repo=https://github.com/letsencrypt/letsencrypt
       dest=/root/letsencrypt
       version=master
       force=yes
  tags: letsencrypt
  
- name: Configure LetsEncrypt
  template: src=etc_letsencrypt_cli.conf.j2 dest=/etc/letsencrypt/cli.conf owner=root group=root
  tags: letsencrypt

- name: Install LetsEncrypt package dependencies
  command: /root/letsencrypt/letsencrypt-auto --help
  register: le_deps_result
  changed_when: "'Bootstrapping dependencies' in le_deps_result.stdout"
  tags: letsencrypt

